config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only:[:index,:new,:show,:create,:edit,:update,:destroy]
  resources :labels
end

app/models/task.rb
class Task < ApplicationRecord
  
  validates :name, presence:true, null:false,length:{maximum:60}
  validates :content, presence:true, null:false
  validates :end_time, presence:true, null:false
#search control
  enum statut: %i[not_started started completed]
  enum priority: %i[low medium high]

  scope :name_search,  -> (text_serach) {where("name LIKE ?", "%#{text_serach}%")}
  scope :status_search,  -> (text_serach) {where(status: text_serach)}
  #post control
  belongs_to :user
  #labelling
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:index,:show, :new, :edit, :destroy]
  before_action :user_check, only:[:show, :edit, :destroy]
  PER = 4
  def index
    if params[:sort_expired]
      @tasks=current_user.tasks.all.order(end_time: :desc).page(params[:page]).per(4)
    elsif params[:sort_priority]
      @tasks=current_user.tasks.all.order(priority: :desc).page(params[:page]).per(4)
    elsif params[:name].blank? && params[:statut]
      @tasks = current_user.tasks.where(statut:params[:statut]).page(params[:page]).per(4)
    elsif params[:name] && params[:statut]
      @tasks = current_user.tasks.where(name: params[:name]).where(statut:params[:statut]).page(params[:page]).per(4)
    else
      @tasks=current_user.tasks.all.order(created_at: :desc).page(params[:page]).per(4)
    end
    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
  end
  def new
    @task = Task.new
  end
  def create
    #@task = Task.new (task_params)
    #@task.user_id = current_user.id
    @task =current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'Task successfully create !'
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end
  def show
  end
  def edit

  end
  def update
    if @task.update(task_params)
      flash[:success] = 'Task successfully update !'
      redirect_to admin_users_path
    else
      render :edit
    end
  end
  def destroy
    @task.destroy
    flash[:success] = 'Task successfully destroy !'
    redirect_to admin_users_path
  end
private
  def task_params
    params.require(:task).permit(:name,:content,:end_time,:statut, :priority , { label_ids: [] })
  end
  def set_task
    @task = Task.find(params[:id])
  end
  def user_check
    redirect_to tasks_path, notice:('access deny') unless current_user.id == @task.user_id || current_user.admin?
  end
  def login_check
    redirect_to new_session_path, notice:('you are not Login, please login or Create new Accompt') unless logged_in?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
      <%= form_with(model:@task,local: true) do |form| %>
          <div class="field">
            <%= form.label:name %>
            <%= form.text_field :name %>
          </div>
          <br>
          <div class="field">
            <%= form.label:content %>
            <%= form.text_area :content %>
          </div>
          <br>
          <div class="field">
            <%= form.label :end_time %>
            <%= form.date_select :end_time %>
          </div>
          <div class="field">
            <%= form.label :statut %>
            <%= form.select(:statut, {not_started: 'not_started', started: 'started', completed: 'completed'}) %>
          </div>
          <div class="field">
            <%= form.label :priority %>
            <%= form.select(:priority, {low: 'low', medium: 'medium', high: 'high' }) %>
          </div>
          <br>
          <div class="field">
            <% current_user.labels.all.each do |label| %>
              <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
              <label style="background-color: aquamarine"><%= label.name %></label>
            <% end %>
          </div>
            <%= form.submit :class=>"btn btn-primary"%>
      <% end %>
</div>
<%=render 'layouts/footer'%>

app/views/tasks/edit.html.erb
<div class="user_top">
  <h4><%= current_user.name %></h4>
  <p><em><%= current_user.email %></em></p>
  <%if logged_in? || current_user.id == @user.id %>
    <div class="action">
      <div class="left">
        <span class=""><%=link_to "#{current_user.name} task list",user_path(current_user.id) %></span>
      </div>
      <div class="right">
        <%if current_user.admin? %>
        <span class=""><%=link_to "user list",admin_users_path %></span>
        <%end%>
      </div>
    </div>
  <%end%>
</div>
<div class="container">
  <div class="container loggin_form">
    <h2>Edit task</h2>
    <%=render 'form' %>
  </div>
</div>
<%=render 'layouts/footer'%>

app/views/tasks/index.html.erb
<%=render 'layouts/search'%>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>End time</th>
      <th>Priority</th>
      <th>Statut</th>
      <th>labels</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_row"><%= link_to "#{task.name}", task  %></td>
        <td><%= task.content %></td>
        <td class="date_row"><%= task.end_time %></td>
        <td class="priority_high"><%= task.priority %></td>
        <td><%= task.statut %></td>
        <td><em><% task.labels.each do |label|%>
              <%= label.name%>,
            <% end %></em>
        </td>
        <td><%= link_to '', edit_task_path(task),:class=>"fas fa-pencil-alt" %></td>
        <td><%= link_to '', task, method: :delete, data: { confirm: 'Are you sure?' },:class=>"far fa-trash-alt" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="label">
  <p><%current_user.labels.each do |label| %>
      <span> <%= label.name%></span>
      <%= link_to "", edit_label_path(label.id),:class=>"fas fa-pencil-alt"%>
      <%= link_to "", label_path(label.id), method: :delete, data: { confirm: 'Are you sure?' },:class=>"fas fa-times trash"%>
     
    <% end %>
    <% if current_user.labels.empty? %>
    <span> <em > add label</em></span>
    <% end %>
    <%= link_to '', new_label_path,:class=>"fas fa-plus" %>
  </p>
</div>
<div>
  <td class="add_task"><%=link_to "New task",new_task_path,:class=>"fas fa-folder-plus" %></td>
</div>
<div class="page">
  <%= paginate @tasks %>
</div>
<%=render 'layouts/footer'%>

app/views/tasks/new.html.erb
<div class="user_top">
  <h4><%= current_user.name %></h4>
  <p><em><%= current_user.email %></em></p>
  <%if logged_in? || current_user.id == @user.id %>
    <div class="action">
      <div class="left">
        <span class=""><%=link_to "task list",user_path(current_user.id) %></span>
      </div>
      <div class="right">
        <%if current_user.admin? %>
        <span class=""><%=link_to "user list",admin_users_path %></span>
        <%end%>
      </div>
    </div>
  <%end%>
</div>
<div class="container">
  <div class="container loggin_form">
    <h2>create new task</h2>
    <%=render 'form' %>
  </div>
</div>
<%=render 'layouts/footer'%>

app/views/tasks/show.html.erb
<div class="user_top">
  <h4><%= current_user.name %></h4>
  <p><em><%= current_user.email %></em></p>
  <%if logged_in? || current_user.id == @user.id %>
    <div class="action">
      <div class="left">
        <span class=""><%=link_to "#{current_user.name} task list",user_path(current_user.id) %></span>
      </div>
      <div class="right">
        <%if current_user.admin? %>
        <span class=""><%=link_to "user list",admin_users_path %></span>
        <%end%>
      </div>
    </div>
  <%end%>
</div>
<div class="container">
  <div class="container show_content taskk_view">
      <h3>name : <%=@task.name%></h3>
      <p>détail : <%=@task.content%></p>
      <p>end time : <%=@task.end_time%></p>
      <p>statut : <%=@task.statut%></p>
      <p>priority : <%=@task.priority%></p>
      <p><em>labels:<% @task.labels.each do |label|%>
            <%= label.name%>,
          <% end %>
      </em></p>


    <span class="task_action"><%= link_to ' edit', edit_task_path(@task.id),:class=>"fas fa-pencil-alt" %></span>
    <span class="task_action"><%= link_to ' delete', task_path(@task.id), method: :delete, data: { confirm: 'Are you sure?' },:class=>"far fa-trash-alt"%></span>

</div>
<%=render 'layouts/footer'%>