config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only:[:index,:new,:show,:create,:edit,:update,:destroy]
  resources :labels
end

app/models/user.rb
class User < ApplicationRecord
    before_destroy :destroy_admin
    before_update :update_admin
    validates :name,  presence: true, length: { maximum: 25  }
    validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, on: :create,
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    has_many :tasks, dependent: :destroy

    has_many :labels, dependent: :destroy
    private
    def destroy_admin
      if User.where(admin: true).count == 1
        user = User.where(admin: true)
        throw :abort if user[0] == self
      end
    end
  
    def update_admin
      if User.where(admin: true).count == 1 && admin == false
        user = User.where(admin: true)
        if user[0] == self
          errors.add(:user, 'you are currently the only administrator. Please choose another administrator before ')
          throw :abort
        end
      end
    end
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin
  before_action :set_user, only:[:show, :edit, :destroy, :update]

  def index
    @users = User.all.order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'user are successfully create'
      redirect_to (admin_users_path)
    else
      flash[:danger] = 'something wrong'
      render :new
    end
  end
  def show
    @task =@user.tasks
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:success]="user update"
      if current_user.admin?
        redirect_to admin_users_path
      else
        redirect_to user_path(current_user.id)
      end
    else
      if current_user.admin?
        flash[:danger] = 'you are currently the only administrator. Please choose another administrator before'
        render :new
      else
        flash[:danger] = 'something wrong'
        render :new
      end
    end
  end
  def destroy
    if @user.destroy
      flash[:success] = 'user are successfully destroy'
      redirect_to (admin_users_path)
    else
      if current_user.admin?
        flash[:danger] = 'you are currently the only administrator. Please choose another administrator before'
        redirect_to admin_users_path
      else
        flash[:danger] = 'something wrong'
        redirect_to admin_users_path
      end
    end
  end
private
def check_admin
  if logged_in?
    redirect_to (root_path) unless current_user.admin?
  else
    redirect_to(new_session_path)
  end
end
def user_params
  params.require(:user).permit(:name, :email, :admin, :password,  :password_confirmation)
end
def set_user
  @user = User.find(params[:id])
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only:[:show, :edit, :update, :destroy]
    before_action :user_check, only: [:index,:show,:edit, :update, :destroy]
    before_action :login_check, only:[:new, :index, :edit]
  
    #def admin_user
     # redirect_to(root_url) unless current_user && current_user.admin?
   # end

    def index
    end
    def new
      @user=User.new
    end
    def create
      @user=User.new(user_params)
      if @user.save
        if logged_in?
          redirect_to admin_users_path
          flash[:success]="account created successfull"
        else
        session[:user_id] = @user.id
        redirect_to users_path
        flash[:success]="account created successfull"
      end
      else
        flash[:danger]="something is wrong !"
        render :new
      end
    end
    def show
    end
    def edit
    end
    def update
      if @user.update(user_params)
        flash[:success]="user update"
        if current_user.admin?
          redirect_to admin_users_path
        else
          redirect_to user_path(current_user.id)
        end
      else
        render :new
      end
    end
    def destroy
      @user.destroy
      redirect_to new_user_path
    end
    private
    def user_params
      params.require(:user).permit(:name,:email,:admin,:password,:password_confirmation)
    end
    def set_user
      @user=User.find(params[:id])
    end

    def user_check
      redirect_to user_path(current_user.id), notice:('access deny') unless current_user == @user || current_user.admin?
    end
    
    def login_check
      redirect_to user_path(current_user.id), notice:('you are already logged') if logged_in?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="container ">
  <% if @user.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
     <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
     </ul>
  </div>
  <% end %>
  <div class="container">
   <%= form_with(model:[:admin, @user], local: true) do |f| %>
   <%= f.label :name, "your name" %>
   <%= f.text_field :name,:class=>"form-control",:id=>"exampleInputEmail1" %>
   <%= f.label :email %>
   <%= f.email_field :email,:type=>"email",:class=>"form-control",:id=>"exampleInputEmail1" %>
   <%= f.label :admin %>
   <%= f.check_box :admin,{}, "true","false" %><br>
   
   <%= f.label :password %>
   <%= f.password_field :password,:type=>"password",:class=>"form-control",:id=>"exampleInputPassword1" %>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation,:type=>"password",:class=>"form-control",:id=>"exampleInputPassword1" %>
  <br>
   <%= f.submit :class=>"btn btn-primary"%>
   <% end %>
   </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="container loggin_form">
    <h2>Edit user role</h2>
    <div class="container ">
      <% if @user.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
         <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
         </ul>
      </div>
      <% end %>
      <div class="container">
       <%= form_with(model: [:admin, @user], local: true) do |f| %>
       <%= f.hidden_field :name,:class=>"form-control",:id=>"exampleInputEmail1" %>
       <%= f.hidden_field :email,
                          :class=>"form-control",:id=>"exampleInputEmail1" %>
       <%= f.label :admin %>
       <%= f.check_box :admin,{}, "true","false" %><br>
       
       <%= f.hidden_field :password,
                          :class=>"form-control",
                          :id=>"exampleInputPassword1" %>
       <%= f.hidden_field :password_confirmation,
                          :class=>"form-control",
                          :id=>"exampleInputPassword1" %>
      <br>
       <%= f.submit :class=>"btn btn-primary"%>
       <% end %>
       </div>
    </div>
  </div>
</div>
<div class="">
  <p id="loggin_form"> <span class="badge badge-pill badge-light"><%=link_to "login",new_session_path %></span></p>
</div>
<%=render 'layouts/footer'%>

app/views/admin/users/index.html.erb
<div class="user_top">
  <%if logged_in? || current_user.id == @user.id %>
    <div class="action">
      <div class="left">
        <span class=""><%=link_to "",edit_user_path(current_user.id),:class=>"fas fa-user-edit" %></span>
        <span class=""><%=link_to " ",user_path(current_user.id),method: :delete, data: { confirm: 'Are you sure?'} ,:class=>"far fa-trash-alt" %></span>
      </div>
      <div class="right">
        <%if current_user.admin? %>
        <span class=""><%=link_to "Users",admin_users_path %></span>
        <span class=""><%= link_to "New user", new_admin_user_path %></span>
        <span class=""><%= link_to "Admin tasks", user_path(current_user.id) %></span>
        <%end%>
      </div>
    </div>
  <%end%>
  <div class="detail">
    <br>
    <h4><%= current_user.name %></h4>
    <p><em><%= current_user.email %></em></p>
   <%=link_to "logout",session_path(current_user.id),method: :delete, data: { confirm: 'Are you sure?'} %>

  </div>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>User name</th>
            <th>Admin</th>
            <th>Task count</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= link_to "#{user.name}", admin_user_path(user)%></td>
                <td><%= user.admin %></td>
                <td><%= user.tasks.count %></td>
                <td><%= link_to "Edit role", edit_admin_user_path(user),:class=>"fas fa-user-edit" %></td>
                <td><%= link_to "Destroy", admin_user_path(user), method: :delete, data: { confirm: 'are you sure ?' },:class=>"far fa-trash-alt" %></td>
            </tr>
        <% end %>
        <tr>
          <td class="add_task"><%=link_to " create new user",new_admin_user_path,:class=>"fas fa-folder-plus" %></td>
        </tr>
    </tbody>
</table>
<%=render 'layouts/footer'%>

app/views/admin/users/new.html.erb
<div class="user_top">
    <div class="action">
        <span class=""><%=link_to "Back",admin_users_path %></span>
    </div>
</div>
<div class="container">
  <div class="container loggin_form">
    <h2>New user</h2>
    <%=render 'form' %>
  </div>
</div>
<%=render 'layouts/footer'%>

app/views/admin/users/show.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Contents</th>
      <th>End-date</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Labels</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task.each do |task| %>
      <tr>
        <td class="task_row"><%= link_to "#{task.name}", task  %></td>
        <td><%= task.content %></td>
        <td class="date_row"><%= task.end_time %></td>
        <td class="priority_high"><%= task.priority %></td>
        <td><%= task.statut %></td>
        <td><em><% task.labels.each do |label|%>
            <%= label.name%>,
               <% end %></em>
          </td>
        <td><%= link_to '', edit_task_path(task),:class=>"fas fa-pencil-alt" %></td>
        </tr>
        <% end %>
        <td><%= link_to 'add label', new_label_path,:class=>"fas fa-folder-plus" %></td>      </tr>
    
  </tbody>
</table>
<%=render 'layouts/footer'%>