config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only:[:index,:new,:show,:create,:edit,:update,:destroy]
  resources :labels
end

app/views/layouts/_footer.html.erb
<footer>
 <p>©2020 DIVE INTO CODE</p>
</footer>

app/views/layouts/_search.html.erb
<div class="user_top">
  <%if logged_in? || current_user.id == @user.id %>
  <div class="action">
    <div class="left">
      <span class=""><%=link_to "",edit_user_path(current_user.id),:class=>"fas fa-user-edit" %></span>
      <span class=""><%=link_to " ",user_path(current_user.id),method: :delete, data: { confirm: 'Are you sure?'} ,:class=>"far fa-trash-alt" %></span>
    </div>
    <div class="right">
      <%if current_user.admin? %>
      <span class=""><%=link_to "users list",admin_users_path %></span>
      <span class=""><%= link_to "create new user", new_admin_user_path %></span>
      <%end%>
    </div>
  </div>
  <%end%>
  <h4><%= current_user.name %></h4>
  <p><em><%= current_user.email %></em></p>
  <%=link_to 'logout',session_path(current_user.id),method: :delete, data: { confirm: 'Are you sure?'} %>
  <div class="search">
    <%= form_with(url: tasks_path, method: :get, local: true) do |f| %>
      <%= f.label(:name, 'name') %>
      <%= f.text_field :name %>
      <%= f.label:statut %>
      <%= f.select :statut, [["not_started", 0 ], ["started", 1 ], ["completed", 2 ] ], include_blank: "veuillez choisir"%>
      <%= f.hidden_field :search, value: 'true' %>
      <%= f.submit'search',:class=>"btn btn-dark" %>
    <% end %>
  </div>
  <div class="search">
    <%= form_with(url: tasks_path, method: :get, local: true) do |f| %>
      <%= f.label :labels, 'search by label'%>
      <%= f.select("label_id", current_user.labels.pluck(:name, :id), {include_blank: true}) %>
      <%= f.submit'Search', name: nil %>
    <% end %>
  </div>
  <span class="nav-top">
    <span><%=link_to " deadline", tasks_path(sort_expired: "true"), :class=>"fas fa-sort-down"%></span>
    <span><%=link_to " priority", tasks_path(sort_priority: "true"),:class=>"fas fa-sort-down"%></span>
  </span>
</div>

app/views/layouts/_task.html.erb
<div class="list_task">
  <span><%=link_to "Home", tasks_path%></span>
  <span><%=link_to "New task", new_task_path,:class=>""%></span>
</div>

app/views/layouts/_top.html.erb
<div class="content">
  <h3>TASK LIST</h3>
  <div class="search">
    <%= form_with(url: tasks_path, method: :get, local: true) do |f| %>
      <%= f.label(:name, 'name') %>
      <%= f.text_field :name %>
      <%= f.label:statut %>
      <%= f.select :statut, [ ["not_started", 0 ], ["started", 1 ], ["completed", 2 ] ]%>
      <%= f.submit'search',:class=>"btn btn-dark" %>
    <% end %>
  </div>
  <span class="nav-top">
    <span><%=link_to " Home", tasks_path, :class=>"fas fa-home"%></span>
    <span><%=link_to " New task", new_task_path,:class=>"fas fa-plus-square"%></span>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THE TASKS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="">
      <% flash.each do |key, value|%>
        <%= content_tag(:div,value,class:"alert alert-#{key}")%>
      <% end%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/user_top.html.erb
<div class="user_top">
  <%if logged_in? || current_user.id == @user.id %>
    <div class="action">
      <div class="left">
        <%unless current_user.admin? %>
        <span class=""><%=link_to "Edit current user",edit_user_path(@user.id),:class=>"fas fa-user-edit" %></span>
        <span class=""><%=link_to "Edit current user ",user_path(@user.id),method: :delete, data: { confirm: 'Are you sure?'} ,:class=>"far fa-trash-alt" %></span>
        <%end%>
      </div>
      <div class="right">
        <%if current_user.admin? %>
        <span class=""><%=link_to "users list",admin_users_path %></span>
        <span class=""><%= link_to "create new user", new_admin_user_path %></span>
        <%end%>
      </div>
    </div>
  <%end%>
  <div class="detail">
    <br>
    <h4><%= @user.name %></h4>
    <p><em><%= @user.email %></em></p>
    <%=link_to 'logout',session_path(current_user.id),method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>

</div>